//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.07 at 06:10:45 PM EEST 
//


package gr.helix.core.web.model.openaire;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for relType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="relType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice maxOccurs="unbounded">
 *           &lt;element name="to" type="{http://namespace.openaire.eu/oaf}relToType"/>
 *           &lt;element name="title" type="{http://namespace.openaire.eu/oaf}optionalClassedSchemedElement"/>
 *           &lt;element name="websiteurl" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *           &lt;choice>
 *             &lt;group ref="{http://namespace.openaire.eu/oaf}relDataSourceGroup"/>
 *             &lt;group ref="{http://namespace.openaire.eu/oaf}relResultGroup"/>
 *             &lt;group ref="{http://namespace.openaire.eu/oaf}relProjectGroup"/>
 *             &lt;group ref="{http://namespace.openaire.eu/oaf}relOrganizationGroup"/>
 *             &lt;group ref="{http://namespace.openaire.eu/oaf}fundingGroup"/>
 *           &lt;/choice>
 *         &lt;/choice>
 *       &lt;/sequence>
 *       &lt;attGroup ref="{http://namespace.openaire.eu/oaf}optionalInferenceAttrGroup"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "relType", propOrder = {
    "toOrTitleOrWebsiteurl"
})
public class RelType {

    @XmlElementRefs({
        @XmlElementRef(name = "to", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "country", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "legalname", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "contracttype", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "title", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "websiteurl", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "pid", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "funding", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "code", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "url", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "officialname", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "resulttype", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "dateofacceptance", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "legalshortname", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "type", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "acronym", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "publisher", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "similarity", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "datasourcetype", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "openairecompatibility", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "collectedfrom", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "datasourcetypeui", type = JAXBElement.class, required = false)
    })
    protected List<JAXBElement<?>> toOrTitleOrWebsiteurl;
    @XmlAttribute(name = "inferred")
    protected Boolean inferred;
    @XmlAttribute(name = "inferenceprovenance")
    protected String inferenceprovenance;
    @XmlAttribute(name = "provenanceaction")
    protected String provenanceaction;
    @XmlAttribute(name = "trust")
    protected String trust;

    /**
     * Gets the value of the toOrTitleOrWebsiteurl property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the toOrTitleOrWebsiteurl property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getToOrTitleOrWebsiteurl().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link RelToType }{@code >}
     * {@link JAXBElement }{@code <}{@link OptionalClassedSchemedElement }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link OptionalClassedSchemedElement }{@code >}
     * {@link JAXBElement }{@code <}{@link OptionalClassedSchemedElement }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link JAXBElement }{@code <}{@link OptionalClassedSchemedElement }{@code >}
     * {@link JAXBElement }{@code <}{@link FundingFlatType }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link ClassedSchemedElement }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link Double }{@code >}
     * {@link JAXBElement }{@code <}{@link ClassedSchemedElement }{@code >}
     * {@link JAXBElement }{@code <}{@link ClassedSchemedElement }{@code >}
     * {@link JAXBElement }{@code <}{@link NamedIdElement }{@code >}
     * {@link JAXBElement }{@code <}{@link ClassedSchemedElement }{@code >}
     * 
     * 
     */
    public List<JAXBElement<?>> getToOrTitleOrWebsiteurl() {
        if (toOrTitleOrWebsiteurl == null) {
            toOrTitleOrWebsiteurl = new ArrayList<JAXBElement<?>>();
        }
        return this.toOrTitleOrWebsiteurl;
    }

    /**
     * Gets the value of the inferred property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isInferred() {
        return inferred;
    }

    /**
     * Sets the value of the inferred property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setInferred(Boolean value) {
        this.inferred = value;
    }

    /**
     * Gets the value of the inferenceprovenance property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInferenceprovenance() {
        return inferenceprovenance;
    }

    /**
     * Sets the value of the inferenceprovenance property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInferenceprovenance(String value) {
        this.inferenceprovenance = value;
    }

    /**
     * Gets the value of the provenanceaction property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProvenanceaction() {
        return provenanceaction;
    }

    /**
     * Sets the value of the provenanceaction property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProvenanceaction(String value) {
        this.provenanceaction = value;
    }

    /**
     * Gets the value of the trust property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTrust() {
        return trust;
    }

    /**
     * Sets the value of the trust property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTrust(String value) {
        this.trust = value;
    }

}
